name: Demo Workflow CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout the master branch
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Step 2a - Run the tag action
      id: tag 
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true # Determine the tag version
    - name: Step 2b - Print previous tag
      run: "echo 'Previous Version: ${{steps.tag.outputs.tag}}'"
    - name: Step 2c - Print new tag
      run: "echo 'New Version: ${{steps.tag.outputs.new_tag}}'"
    - name: Step 3 - Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Step 4 - Build with Maven
      run: mvn -B package -DartifactId.version=${{steps.tag.outputs.tag}} --file pom.xml
    - name: Step 5 - Tag release on Maven
      run: mvn versions:set -DnewVersion=${{steps.tag.outputs.tag}}
    - name: Step 5 - List current directory
      run: ls -al
    - name: Step 6 - List the target directory
      run: |
        cd target
        ls -al