name: Demo Workflow CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout the master branch
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Step 2 - Run the tag action 
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true # Determine the tag version
