name: Demo Workflow CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout the master branch
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Step 2a - Run the tag action
      id: tag 
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true # Determine the tag version
    - name: Step 2b - Print previous tag
      run: "echo 'Previous Version: ${{steps.tag.outputs.tag}}'"
    - name: Step 2c - Print new tag
      run: "echo 'New Version: ${{steps.tag.outputs.new_tag}}'"
    - name: Step 3 - Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github 
    - name: Step 4 - Update tag release on Maven
      run: mvn -B release:update-versions -DdevelopmentVersion=${{steps.tag.outputs.new_tag}}-SNAPSHOT
    - name: Step 5 - Build with Maven
      run: mvn -B package --file pom.xml
    - name: Step 6 - List current directory
      run: ls -al
    - name: Step 7 - List the target directory
      run: |
        cd target
        ls -al
    - name: Step 8 - Publish to GitHub Packages
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Step 9 - Create a Release
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        args: Release ${{steps.tag.outputs.new_tag}}